name: flutter_basic
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  audioplayers: ^6.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.0.1
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf

linter:
  rules:
    prefer_const_constructors: false
